ARCH=arm
CROSS_COMPILE=arm-linux-gnueabi-

obj-m += pdval.o
KDIR:=/home/aniruddha/workspace/vlc/u-boot-2016.01/kernel/kernel
all:
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KDIR) M=$(PWD) modules

clean:
	make ARCH=$(ARCH) CROSS_COMPILE=$(CROSS_COMPILE) -C $(KDIR) M=$(PWD) clean

